default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: activerecord_associations_from_scratch_development

test:
  <<: *default
  database: activerecord_associations_from_scratch_test
